const mongoose = require('mongoose')
const Resorts = require('./models/resorts')
const User = require('./models/users')
const { dbURI } = require('./config/environment')
const axios = require('axios')

mongoose.connect(
  dbURI,

  { useNewUrlParser: true, useUnifiedTopology: true, useCreateIndex: true },
  (err) => {

    if (err) return console.log(err)

    console.log('Mongoose connected!')
    mongoose.connection.db.dropDatabase()

      .then(() => {
        return User.create([
          {
            username: 'Admin',
            email: 'admin@admin.com',
            password: 'admin',
            passwordConfirmation: 'admin',
            image: 'https://i.imgur.com/4f1MbGO.png?1',
            isAdmin: true,
            firstname: 'Firstname',
            lastname: 'Lastname',
            bio: 'This is my bio section. A brief sentence about myself and my interests go here...',
            favourites: [],
            ski_or_board: '',
            favourite_region: '',
            hometown: '',
            experience: '',
            favourite_brand: ''

          },
          {
            username: 'Daniel94',
            email: 'daniel@daniel.com',
            password: 'daniel',
            passwordConfirmation: 'daniel',
            image: 'https://i.imgur.com/X99kVmw.jpg',
            isAdmin: true,
            firstname: 'Daniel',
            lastname: 'Tockan',
            bio: '26, software developer. Loves to ski and board from time to time!',
            favourites: [],
            ski_or_board: '',
            favourite_region: '',
            hometown: '',
            experience: '',
            favourite_brand: ''

          },
          {
            username: 'Kasjan_',
            email: 'kasjan@kasjan.com',
            password: 'kasjan',
            passwordConfirmation: 'kasjan',
            image: 'https://i.imgur.com/ZP4QyR3.jpg',
            isAdmin: true,
            firstname: 'Kasjan',
            lastname: 'Hinc',
            bio: 'Fill this out Kas...',
            favourites: [],
            ski_or_board: '',
            favourite_region: '',
            hometown: '',
            experience: '',
            favourite_brand: ''

          },
          {
            username: 'SeanF69',
            email: 'sean@sean.com',
            password: 'sean',
            passwordConfirmation: 'sean',
            image: 'https://i.imgur.com/9V2oI0A.jpg',
            isAdmin: true,
            firstname: 'Sean',
            lastname: 'Fenelon',
            bio: 'Fill this out Sean...',
            favourites: [],
            ski_or_board: '',
            favourite_region: '',
            hometown: '',
            experience: '',
            favourite_brand: ''

          },
          {
            username: 'OAlawi',
            email: 'omar@omar.com',
            password: 'omar',
            passwordConfirmation: 'omar',
            image: 'https://i.imgur.com/BErZgrT.jpg',
            isAdmin: true,
            firstname: 'Omar',
            lastname: 'Alawi',
            bio: 'Fill this out Omar...',
            favourites: [],
            ski_or_board: '',
            favourite_region: '',
            hometown: '',
            experience: '',
            favourite_brand: ''

          },
          {
            username: 'Test',
            email: 'test@test.com',
            password: 'test',
            passwordConfirmation: 'test',
            image: 'https://i.imgur.com/ioS25on.jpg',
            isAdmin: false,
            firstname: 'Test',
            lastname: 'Snowboader',
            favourites: [],
            ski_or_board: '',
            favourite_region: '',
            hometown: '',
            experience: '',
            favourite_brand: ''

          }
        ])
      })

      .then(users => {
        console.log(`${users.length} users have been created`)
        return users
      })
      //hmm
      .then((users) => {
        return Resorts.create([

          {
            name: 'Val Thorens',
            country: 'France',
            top_elevation: 3568,
            bottom_elevation: 1650,
            lon: 6.58000,
            lat: 45.29806,
            image: 'https://i.imgur.com/LumFgEX.jpg',
            user: users[0],
            description: 'With the access of the Three Valleys, Val Thorens have one of the largest skiing area in the world! Beginner, intermidates and experts will all find a challenge here!',
            skilifts: '137',
            openingtimes: '08:30 - 16:30',
            slopeslength: '600km',
            adultticket: '€64.50,-',
            childticket: '€51.60,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Val D-Isere',
            country: 'France',
            top_elevation: 3456,
            bottom_elevation: 1850,
            lon: 6.9802,
            lat: 45.4480,
            image: 'https://i.imgur.com/nNlWf6I.jpg',
            user: users[0],
            description: 'This world-class resort has earned its reputation as one of France’s top ski destinations. Val d’Isère has something for skiers and boarders of all levels: Olympic and World Cup runs, a wealth of fantastic off-piste opportunities and a varied selection of pistes including greens high up on the mountain.',
            skilifts: '82',
            openingtimes: '09:30 - 16:30',
            slopeslength: '300km',
            adultticket: '€62,-',
            childticket: '€50,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Tignes',
            country: 'France',
            top_elevation: 3450,
            bottom_elevation: 1550,
            lon: 6.9056,
            lat: 45.4683,
            image: 'https://i.imgur.com/iL5OeXI.jpg',
            user: users[0],
            description: 'At Tignes, you can ski before and after everyone else. That’s the motto of this large resort, which offers summer glacier skiing and a winter season stretching from September to May. With 150km of runs and such a long season, Tignes really does have something for everyone, but intermediate and advanced skiers are especially served. Freestylers and riders will also feel at home, since Tignes was one of France’s first resorts to promote alternative ski culture and continues to welcome it with open arms.',
            skilifts: '82',
            openingtimes: '08:30 - 16:30',
            slopeslength: '200km',
            adultticket: '€62,-',
            childticket: '€50,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Morzine',
            country: 'France',
            top_elevation: 2466,
            bottom_elevation: 1000,
            lon: 6.7089,
            lat: 46.1792,
            image: 'https://i.imgur.com/RWPLVVE.jpg',
            user: users[0],
            description: 'Morzine is one of 14 resorts in the massive Portes du Soleil ski area (650km) which straddles the Franco-Swiss border. With 52 hotels and 41 bars and restaurants, it’s a concentration of ski holiday facilities, but still manages to pull off that authentic mountain village feel.',
            skilifts: '137',
            openingtimes: '08:30 - 16:30',
            slopeslength: '600km',
            adultticket: '€64.50',
            childticket: '€51.60',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Les Deux Alpes',
            country: 'France',
            top_elevation: 3600,
            bottom_elevation: 1350,
            lon: 6.1249,
            lat: 45.0176,
            image: 'https://i.imgur.com/mpkRvho.jpg',
            user: users[0],
            description: 'Ballsy, young boarders launch themselves at Les 2 Alpes’ challenging off-piste, world-class snowpark and energetic party scene. That said, Les 2 Alpes has plenty to offer all: The high and varied slopes are largely north-facing, so hold the snow well, and afford excellent views. There is also a snow-sure glacier for all abilities.',
            skilifts: '46',
            openingtimes: '09:17 - 17:00',
            slopeslength: '200km',
            adultticket: '€53,-',
            childticket: '€42.50,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Les Arcs',
            country: 'France',
            top_elevation: 3226,
            bottom_elevation: 1200,
            lon: 6.8296,
            lat: 45.5722,
            image: 'https://i.imgur.com/ewWY8pB.jpg',
            user: users[0],
            description: 'Les Arcs is best for intermediates, experts, freestylers. Highlights: Car-free villages, beautiful views of Mont Blanc, snowsure slopes, varied skiing with lots of long descents, wooded runs, plenty of challenging steeps, a huge amount of off-piste and a leading terrain park with snowboarder-friendly draglift. ',
            skilifts: '47',
            openingtimes: '08:30 - 16:30',
            slopeslength: '200km',
            adultticket: '€55,-',
            childticket: '€44,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Avoriaz',
            country: 'France',
            top_elevation: 2277,
            bottom_elevation: 1127,
            lon: 6.7751,
            lat: 46.1921,
            image: 'https://i.imgur.com/6Sv9m4M.jpg',
            user: users[0],
            description: 'Car-free, sunny village with compact centre, ski-in/ski-out lodgings, shady snowsure slopes, great position on the Portes du Soleil circuit, leading resort for freestylers (five terrain parks and a super-pipe), plenty of good off-piste, access to the legendary Swiss Wall, and a renowned kids club.',
            skilifts: '172',
            openingtimes: '09:00 - 17:00',
            slopeslength: '580km',
            adultticket: '€59,-',
            childticket: '€44,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Kitzbuhel',
            country: 'Austria',
            top_elevation: 2000,
            bottom_elevation: 800,
            lon: 12.3925,
            lat: 47.4492,
            image: 'https://i.imgur.com/z7TAVEn.jpg',
            user: users[0],
            description: 'Kitzbühel is an idyllic alpine village, within easy reach of three airports, boasting reliable snowfall and a variety of ski runs - what more could you want?',
            skilifts: '57',
            openingtimes: '08:30 - 16:30',
            slopeslength: '181km',
            adultticket: '€59.50,-',
            childticket: '€29.50,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'St Anton am Arlberg',
            country: 'Austria',
            top_elevation: 2811,
            bottom_elevation: 1304,
            lon: 10.2682,
            lat: 47.1296,
            image: 'https://i.imgur.com/1rhJJyj.jpg',
            user: users[0],
            description: 'Skiing here can be challenging, especially in the Galzig area, but your pass gives you access to a substantial 305km of varied terrain in the Ski Arlberg area.',
            skilifts: '88',
            openingtimes: '08:45 - 16:30',
            slopeslength: '303km',
            adultticket: '€59,-',
            childticket: '€35,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Obertauern',
            country: 'Austria',
            top_elevation: 2313,
            bottom_elevation: 1630,
            lon: 13.5471,
            lat: 47.2517,
            image: 'https://i.imgur.com/5thwBfq.jpg',
            user: users[0],
            description: 'The ski resort Obertauern is located in the Lungau (Austria, Salzburg (Salzburger Land)) and in Obertauern (Austria, Salzburg (Salzburger Land)). For skiing and snowboarding, there are 100 km of slopes available. 26 lifts transport the guests. The winter sports area is situated between the elevations of 1,630 and 2,313 m.',
            skilifts: '26',
            openingtimes: '09:00 - 16:00',
            slopeslength: '100km',
            adultticket: '€49,-',
            childticket: '€37,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'St. Moritz',
            country: 'Switzerland',
            top_elevation: 3022,
            bottom_elevation: 1720,
            lon: 9.8190,
            lat: 46.5076,
            image: 'https://i.imgur.com/e6hqVqF.jpg',
            user: users[0],
            description: 'The ski resort St. Moritz – Corviglia is located in Engadin St. Moritz (Switzerland, Eastern Switzerland, Graubünden). For skiing and snowboarding, there are 155 km of slopes and 8 km of ski routes available. 24 lifts transport the guests. The winter sports area is situated between the elevations of 1,720 and 3,022 m. The Corviglia is the home mountain of the world-famous winter sports village of St. Moritz. Optimally groomed slopes welcome skiers to ski between Marguns, Corviglia, Salastrains, Signal, Munt da San Murezzan as well as the highest point, Piz Nair (3057 m). Access points to the winter sports resort are in St. Moritz Dorf, St. Moritz Bad, Suvretta (community of St. Moritz) and Celerina. FIS-quality slopes, endless skiing possibilities, cosmopolitan visitors as well as the "Champagne" atmosphere make St. Moritz one of the most famous skiing areas in the world. In 1928 and 1948, St. Moritz hosted the Winter Olympic Games.',
            skilifts: '24',
            openingtimes: '07:45 - 17:00',
            slopeslength: '155km',
            adultticket: '',
            childticket: '',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Betelberg ',
            country: 'Switzerland',
            top_elevation: 2001,
            bottom_elevation: 1075,
            lon: 7.4067,
            lat: 46.4260,
            image: 'https://i.imgur.com/NvpWuCH.jpg',
            user: users[0],
            description: 'The ski resort Betelberg – Lenk is located in Lenk-Simmental (Switzerland, Espace Mittelland, Bern, Bernese Oberland). For skiing and snowboarding, there are 42 km of slopes available. 10 lifts transport the guests.',
            skilifts: '10',
            openingtimes: '08:30 - 16:30',
            slopeslength: '42km',
            adultticket: '€53,-',
            childticket: '€44,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Winterberg',
            country: 'Germany',
            top_elevation: 820,
            bottom_elevation: 630,
            lon: 8.5194,
            lat: 51.1916,
            image: 'https://i.imgur.com/Mjnvlf0.jpg',
            user: users[0],
            description: 'The ski resort Winterberg (Skiliftkarussell) is located in the Sauerland (Germany, Central Uplands of Germany (Deutsche Mittelgebirge)). For skiing and snowboarding, there are 27.5 km of slopes available. 21 lifts transport the guests. The winter sports area is situated between the elevations of 630 and 820 m.A ski resort second to none. State-of-the-art chair lifts, drag lifts and conveyor belts take winter athletes of all levels to the 34 runs of the area. The diversified ski area encompasses 7 mountains that are all interconnected and offers two dedicated toboggan lifts. A high-performance snow-making system guarantees snow on 28 pistes. 14 of the pistes are equipped with floodlights, enabling night skiing and après-ski fun on Wednesdays, Fridays and Saturdays. Nine snowcats set to work at night to ensure you´ll find perfect conditions when you get up in the morning. After all the excitement enjoy a meal in one of the resorts comfortable traditional lodges.',
            skilifts: '21',
            openingtimes: '09:00 - 16:30',
            slopeslength: '27.5km',
            adultticket: '€37,-',
            childticket: '€25,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Mammoth Mountain',
            country: 'USA',
            top_elevation: 2811,
            bottom_elevation: 1304,
            lon: -119.0326,
            lat: 37.6308,
            image: 'https://i.imgur.com/J8fatb3.jpg',
            user: users[0],
            description: 'Mammoth Mountain Ski Area boasts the highest elevation, 11,053’, for skiing and snowboarding in the state of California. Located along the eastern edge of California’s Sierra Nevada Mountain Range, Mammoth Mountain is a fan favorite for it’s 3,100 vertical feet of skiing, 3,500 skiable acres, 400” of annual snowfall and an average winter season that lasts from November to June. Mammoth’s accommodations include their Main Lodge, Canyon Lodge and Eagle Lodge, all conveniently located near the mountain, and in addition to their impeccable skiing and snowboarding, the mountain also offers cross-country and snowshoeing terrain, Snowmobile Adventures, and luxurious Snowcat Tours.',
            skilifts: '25',
            openingtimes: '08:30 - 16:00',
            slopeslength: '89.8km',
            adultticket: '$199,-',
            childticket: '$80,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Sudelfeld',
            country: 'Germany',
            top_elevation: 1563,
            bottom_elevation: 850,
            lon: 12.0407,
            lat: 47.6712,
            image: 'https://i.imgur.com/UfF1BmN.jpg',
            user: users[0],
            description: 'The ski resort Sudelfeld – Bayrischzell is located in the Alpine Region Tegernsee-Schliersee (Germany, Bavaria (Bayern).The ski resort extends from the village of Bayrischzell up to the Sudelfeld (from which it takes its name) and the Vogelsang at 1,563 metres. The mainly wide and extensive runs in the winter sports resort in the Mangfall Mountains offer beautiful panoramic views of the Bavarian Alps and towards the Inn Valley (Inntal) and Kaiser Mountains.',
            skilifts: '14',
            openingtimes: '08:30 - 16:30',
            slopeslength: '31km',
            adultticket: '€41,-',
            childticket: '€35,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Whistler',
            country: 'Canada',
            top_elevation: 2284,
            bottom_elevation: 675,
            lon: -122.9574,
            lat: 50.1163,
            image: 'https://i.imgur.com/21oAZwq.jpg',
            user: users[0],
            description: 'The ski resort Whistler Blackcomb is located in the Squamish-Lillooet Regional District (Canada, British Columbia, Vancouver, Coast & Mountains). For skiing and snowboarding, there are 200 km of slopes and 50 km of ski routes available. 23 lifts transport the guests. The winter sports area is situated between the elevations of 675 and 2,284 m.',
            skilifts: '23',
            openingtimes: '08:30 - 16:00',
            slopeslength: '200km',
            adultticket: '$64.50,-',
            childticket: '$51.60,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'The Remarkables',
            country: 'New Zealand',
            top_elevation: 1943,
            bottom_elevation: 1586,
            lon: 168.6616,
            lat: -45.0302,
            image: 'https://i.imgur.com/NC7YM6e.jpg',
            user: users[0],
            description: 'Find your freedom at The Remarkables ski resort in Queenstown. Explore the sunny alpine slopes overlooking Queenstown New Zealand.',
            skilifts: '4',
            openingtimes: '09:00 - 16:00',
            slopeslength: '10km',
            adultticket: 'NZ$ 129,-',
            childticket: 'NZ$ 69,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Rusutsu',
            country: 'Japan',
            top_elevation: 2811,
            bottom_elevation: 1304,
            lon: 140.8969,
            lat: 42.7484,
            image: 'https://i.imgur.com/eGRYAhk.jpg',
            user: users[0],
            description: 'The Rusutsu Ski Resort in Hokkaido is absolute heaven for experienced powder hounds or powder hounds on their "L" plates. With an average annual snowfall of 13 metres, the Rusutsu Resort has some of the most incredible powder and tree skiing to be found anywhere in the world. Frequently the powder is incredibly dry; you blast right through it with virtually no resistance. It is an absolute bliss! Rusutsu Hokkaido is great for a day trip from Niseko to experience some Japow nirvana, but it’s even better if you book a multi-day stay at Rusutsu.',
            skilifts: '18',
            openingtimes: '09:00 - 20:00',
            slopeslength: '42km',
            adultticket: '¥ 6200',
            childticket: '¥ 3200',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Jackson Hole',
            country: 'USA',
            top_elevation: 3185,
            bottom_elevation: 1924,
            lon: -110.8279,
            lat: 43.5875,
            image: 'https://i.imgur.com/TeiS6Ne.jpg',
            user: users[0],
            description: 'Jackson Hole Mountain Resort is a North American ski resort on steroids. Jackson Hole Wyoming is an exceptional ski resort due to the snow, the amazing steep and challenging terrain, the backcountry, the village, and the lift infrastructure. It’s so easy to see why so many people flock there to live and call themselves “a local”! Jackson Hole Ski Resort is so perfect that the Powderhounds would consider it to be the best US ski resort, however…and it’s a big however…. everyone knows how fabulous it is and it’s become completely over-run. On a powder day, the Jackson Hole Ski Resort can be feral, the lift lines ridiculously long, fresh powder gone in-bounds within half an hour (and gone within an hour in the sidecountry), and good luck if you need to drive or get a bus from the town of Jackson. Yet if it’s not a powder day mid-week, all the locals don’t bother turning up, and it’s a fairly peaceful ski resort. Weekends can be a different matter when lots of Ikon Pass holders arrive en masse.',
            skilifts: '13',
            openingtimes: '09:00 - 16:00',
            slopeslength: '116km',
            adultticket: 'US$ 175,-',
            childticket: 'US$ 105,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Aspen Snowmass',
            country: 'USA',
            top_elevation: 3813,
            bottom_elevation: 2470,
            lon: -106.9491,
            lat: 39.2084,
            image: 'https://i.imgur.com/2asZ11H.jpg',
            user: users[0],
            description: 'Snowmass Ski Area is massive enough to offer up every type of terrain from serene to extreme. 21 lifts deliver you to more than 3300 acres with 94 trails.',
            skilifts: '16',
            openingtimes: '08:30 - 15:30',
            slopeslength: '237km',
            adultticket: 'US$ 184',
            childticket: 'US$ 126',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Vail',
            country: 'USA',
            top_elevation: 3527,
            bottom_elevation: 2475,
            lon: -106.3742,
            lat: 39.6403,
            image: 'https://i.imgur.com/z1zcrW5.jpg',
            user: users[0],
            description: 'The Vail ski resort is one of the most famous ski resorts in the USA. It lies in the middle of the Rocky Mountains. The modern elegance and the timeless style of the holiday village is intertwined with the lifestyle of the former West.',
            skilifts: '25',
            openingtimes: '08:30 - 16:00',
            slopeslength: '234km',
            userRating: 4,
            numOfRatings: 0,
            adultticket: 'US$ 219,-',
            childticket: 'US$ 151,-'
          },
          {
            name: 'Alta',
            country: 'USA',
            top_elevation: 3374,
            bottom_elevation: 2600,
            lon: -111.6386,
            lat: 40.5884,
            image: 'https://i.imgur.com/wZAjU5T.jpg',
            user: users[0],
            description: 'Alta is one of the oldest ski resorts in the US (it opened in 1939) and it retains some of its old-fashioned traditions, the most obvious being the prohibition of snowboarders. Despite significant protests and threatened legal action from some snowboarders, the tradition of skiing remains and only those with two sticks are allowed.',
            skilifts: '8',
            openingtimes: '09:15 - 16:30',
            slopeslength: '116km',
            userRating: 4,
            numOfRatings: 0,
            adultticket: 'US$ 125,-',
            childticket: 'US$ 65,-'
          },
          {
            name: 'Revelstoke',
            country: 'Canada',
            top_elevation: 2225,
            bottom_elevation: 512,
            lon: -118.1957,
            lat: 50.9981,
            image: 'https://i.imgur.com/UVT4qeu.jpg',
            user: users[0],
            description: 'Get revved up and get stoked at Revelstoke Mountain Resort! Corny catch phrases aside, Revelstoke ski resort is continuing to transform itself into becoming one of the biggest and best resorts in Canada. Revelstoke Canada has long been known by cat skiers and heli skiers for the legendary Selkirk powder that falls in abundance.',
            skilifts: '5',
            openingtimes: '08:30 - 15:30',
            slopeslength: '55km',
            adultticket: 'C$ 129,-',
            childticket: 'C$ 46,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Perisher',
            country: 'Australia',
            top_elevation: 2054,
            bottom_elevation: 1720,
            lon: 148.4094,
            lat: -36.4055,
            image: 'https://i.imgur.com/QsyCGul.jpg',
            user: users[0],
            description: 'Perisher NSW is a leading Australian ski resort with plenty of bells and whistles. By Australian standards, Perisher Ski Resort is mega, with the largest skiable terrain and the greatest numbers of lifts in Australia as well as the Southern hemisphere.',
            skilifts: '41',
            openingtimes: '08:30 - 17:00',
            slopeslength: '100km',
            adultticket: 'AU$ 64.50,-',
            childticket: 'AU$ 51.60,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Białka Tatrzańska',
            country: 'Poland',
            top_elevation: 910,
            bottom_elevation: 680,
            lon: 20.1049,
            lat: 49.3945,
            image: 'https://i.imgur.com/t8V95q7.jpg',
            user: users[0],
            description: 'The ski resort Białka Tatrzańska – Kotelnica/​Kaniówka/​Bania is located in Lesser Poland Voivodeship (Poland). For skiing and snowboarding, there are 18.3 km of slopes available. 19 lifts transport the guests. The winter sports area is situated between the elevations of 680 and 910 m. Bialka Tatrzańska consists of three ski resorts: Kotelnica, Kaniówka and Bania. Together, they form one of the largest and most modern ski resorts in Poland. You can ski all of them with one ski pass. Further investments are planned for the future.',
            skilifts: '19',
            openingtimes: '09:00 - 21:00',
            slopeslength: '100km',
            adultticket: '€25,-',
            childticket: '€22,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Bear Mountain',
            country: 'USA',
            top_elevation: 2684,
            bottom_elevation: 2176,
            lon: -116.8609,
            lat: 34.2277,
            image: 'https://i.imgur.com/oUZvlIW.jpg',
            user: users[0],
            description: 'Located in Southern California’s San Bernardino Mountains, Bear Mountain offers a 200-acre winter playground for skiers and snowboarders. Along with Snow Summit, Bear Mountain makes up the Big Bear Mountain Resort.',
            skilifts: '9',
            openingtimes: '08:30 - 16:30',
            slopeslength: '27.2km',
            adultticket: '$94.50,-',
            childticket: '$71.60,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Nevados de Chillan',
            country: 'Chile',
            top_elevation: 1650,
            bottom_elevation: 450,
            lon: -71.3989,
            lat: -36.8453,
            image: 'https://i.imgur.com/Tbkp6qO.jpeg',
            user: users[0],
            description: 'The Nevados de Chillan ski and snowboard terrain is smokin’ – literally considering that the ski resort sits on the flanks of three very active volcanoes. Nevados de Chillan in Chile is great for beginners and intermediates, but the feature of this ski resort is the interesting off-piste terrain that’s come about from a history of rivers of lava flow (none of them recent!). With lots of space and very few people heading off-piste, powder hounds will probably find lots of freshies.',
            skilifts: '20',
            openingtimes: '08:30 - 16:30',
            slopeslength: '50km',
            adultticket: 'CLP48,000,-',
            childticket: 'CLP38,000,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Telluride',
            country: 'USA',
            top_elevation: 4000,
            bottom_elevation: 2500,
            lon: -107.8123,
            lat: 37.9375,
            image: 'https://i.imgur.com/4Il8cKo.jpeg',
            user: users[0],
            description: 'Telluride Ski Resort boasts incredible views of the San Juan Mountains and is home to more than 2,000 acres of lift-accessible terrain. Telluride’s 4,425 feet of vertical is accessed via 19 lifts and 148 runs. With a lift-served elevation of 12,515 feet and a maximum elevation of 13,150 feet, the mountain has no trouble holding onto its snow - more than 280 inches of average snowfall. Telluride’s terrain ranges from beginner to intermediate, with four hike-to terrain areas for advanced and expert skiers. The ski area offers multiple terrain parks for all skill levels as well as 10 kilometers of Nordic skiing.',
            skilifts: '19',
            openingtimes: '08:30 - 16:30',
            slopeslength: '200km',
            adultticket: 'US$ 99,-',
            childticket: 'US$ 54,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Keystones',
            country: 'USA',
            top_elevation: 3800,
            bottom_elevation: 2830,
            lon: -105.9347,
            lat: 39.5792,
            image: 'https://i.imgur.com/oqIB3TZ.jpeg',
            user: users[0],
            description: 'You will not find a more family-friendly ski resort than Keystone, Colorado. Located a mere 100 miles west of the Denver International Airport, Keystone’s three distinct mountain peaks, 20 lifts and 128 runs will challenge skiers and riders of all levels and ages. Rising to a summit elevation of 12,408 feet and a base elevation of 9,280 feet, Keystone offers 3,148 acres of skiable space and even the opportunity to night ski. In fact, Keystone resort has the longest day of skiing in Colorado! ',
            skilifts: '20',
            openingtimes: '08:30 - 16:30',
            slopeslength: '190km',
            adultticket: 'US$ 99,-',
            childticket: 'US$ 54,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Lake Louise',
            country: 'Canada',
            top_elevation: 2637,
            bottom_elevation: 1645,
            lon: -116.1773,
            lat: 51.4254,
            image: 'https://i.imgur.com/5c6SFjJ.jpeg',
            user: users[0],
            description: 'Nestled in the heart of Banff National Park, Lake Louise is home to 4,200 acres of skier and rider accessible terrain. Featured as the largest resort of the Big 3 (Banff, Lake Louise and Sunshine), spectacular views accompany Lake Louises longest run at 8 kilometers (5 miles) and a total vertical rise of 991 meters (3,250 feet). There are also four terrain parks. At Lake Louise, skiers and riders of all ages and abilities will find something that meets their needs.',
            skilifts: '10',
            openingtimes: '08:30 - 16:30',
            slopeslength: '120km',
            adultticket: 'C$ 110,-',
            childticket: 'C$ 60,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Mt. Norquay',
            country: 'Canada',
            top_elevation: 2450,
            bottom_elevation: 1605,
            lon: -115.5978,
            lat: 51.2029,
            image: 'https://i.imgur.com/To36dJy.jpeg',
            user: users[0],
            description: 'The smallest of the Ski Big 3 Banff resorts, Mount Norquay is a local gem in the Canadian Rockies. Do not be fooled by the size of Mount Norquay, for the scenic beauty is that of a picture perfect postcard. As one of the best-kept secrets of the Canadian Rockies, Mount Norquay is a perfect introductory mountain to Sunshine Village and Lake Louise Ski Resort on the Big3 ticket. Mount Norquay is a world heritage site and the birthplace of skiing within the Canadian Rockies',
            skilifts: '6',
            openingtimes: '08:30 - 16:30',
            slopeslength: '70km',
            adultticket: 'C$ 110,-',
            childticket: 'C$ 60,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Snowbird',
            country: 'USA',
            top_elevation: 3352,
            bottom_elevation: 2365,
            lon: -111.6556,
            lat: 40.5829,
            image: 'https://i.imgur.com/o0Gg7sv.jpeg',
            user: users[0],
            description: 'Snowbird’s 2,500 skiable acres are accessed via 1 tram and 10 chairlifts, including 6 high-speed detachable quads and 4 doubles. The Utah ski resort has a summit of 11,000 feet and a base elevation of 7,760 feet, with a vertical drop of 3,240 feet. Snowbird averages approximately 500 inches of snowfall per year. For skiers and riders looking to develop their skills, Snowbird’s Mountain School is the perfect place to learn, offering everything from private instruction and class lessons to women’s ski and snowboard camps.',
            skilifts: '11',
            openingtimes: '08:30 - 16:30',
            slopeslength: '70km',
            adultticket: 'US$ 80,-',
            childticket: 'US$ 40,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Taos Ski Valley',
            country: 'USA',
            top_elevation: 3800,
            bottom_elevation: 2804,
            lon: -105.4545,
            lat: 36.5960,
            image: 'https://i.imgur.com/FoiTMDz.jpeg',
            user: users[0],
            description: 'Yes, you can ski in New Mexico! Taos Ski Valley is the largest ski resort in New Mexico, with almost 1,300 skiable acres. Located 20 miles north of Taos, 72 miles north of Santa Fe and 150 miles north of Albuquerque, this northern New Mexico ski area offers a relaxed, friendly atmosphere and a great variety of runs, including two areas for only expert skiers. ',
            skilifts: '14',
            openingtimes: '08:30 - 16:30',
            slopeslength: '80km',
            adultticket: 'US$ 85,-',
            childticket: 'US$ 45,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Big Sky',
            country: 'USA',
            top_elevation: 3400,
            bottom_elevation: 2284,
            lon: -111.3080,
            lat: 45.2618,
            image: 'https://i.imgur.com/P5OLUQI.jpeg',
            user: users[0],
            description: 'Located in southwest Montana (approximately 50 miles south of Bozeman and an hour north of West Yellowstone), Big Sky Resort provides visitors with many different amenities, a well-developed infrastructure and over 5,850 acres of skiable terrain. Big Sky services its 4,350 feet of vertical via 24 chair lifts and 12 surface lifts. The ski area has a summit elevation of 11,166 feet and sees an average annual snowfall of more than 400 inches. The resort has been lauded for its incredible vertical drop and also the very minimal wait times due to its advanced lift system. ',
            skilifts: '36',
            openingtimes: '08:30 - 16:30',
            slopeslength: '180km',
            adultticket: 'US$ 90,-',
            childticket: 'US$ 45,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Sunshine Village',
            country: 'Canada',
            top_elevation: 2730,
            bottom_elevation: 1660,
            lon: -115.7633,
            lat: 51.1152,
            image: 'https://i.imgur.com/SSxPRSu.jpeg',
            user: users[0],
            description: 'Situated high along the Continental Divide in Banff National Park, Sunshine Village is home to breathtaking views and one of Canada’s longest ski seasons. Sunshine Village is Canada’s highest elevated resort and is located in the heart of Banff National Park. The ski area encompasses more than 3,300 skiable acres and terrain ranges from long groomed runs to steep expert trails. ',
            skilifts: '12',
            openingtimes: '08:30 - 16:30',
            slopeslength: '90km',
            adultticket: 'C$ 90,-',
            childticket: 'C$ 45,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Kicking Horse',
            country: 'Canada',
            top_elevation: 2450,
            bottom_elevation: 1190,
            lon: -117.0483,
            lat: 51.2976,
            image: 'https://i.imgur.com/WcYvr4i.jpeg',
            user: users[0],
            description: 'Kicking Horse Mountain Resort is a great destination for skiers and riders looking for a diverse mix of challenging terrain and excellent snow conditions. Located about 14km outside of Golden, British Columbia, Kicking Horse features one of the longest vertical drops in North America. The ski area is home to large alpine bowls, long steep chutes and short lift lines.',
            skilifts: '5',
            openingtimes: '08:30 - 16:30',
            slopeslength: '50km',
            adultticket: 'C$ 60,-',
            childticket: 'C$ 35,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Niseko United',
            country: 'Japan',
            top_elevation: 1188,
            bottom_elevation: 255,
            lon: 140.6479,
            lat: 42.8489,
            image: 'https://i.imgur.com/6VNfsVe.jpg',
            user: users[0],
            description: 'The ski resort Niseko United – Annupuri/​Grand Hirafu/​Hanazono/​Niseko Village is located on Hokkaido (Japan). For skiing and snowboarding, there are 50.8 km of slopes available. 32 lifts transport the guests. The winter sports area is situated between the elevations of 255 and 1,188 m.',
            skilifts: '32',
            openingtimes: '08:30 - 20:30',
            slopeslength: '50.8km',
            adultticket: '¥ 8000,-',
            childticket: '¥ 6400,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Niseko United',
            country: 'Japan',
            top_elevation: 1188,
            bottom_elevation: 255,
            lon: 140.6479,
            lat: 42.8489,
            image: 'https://i.imgur.com/6VNfsVe.jpg',
            user: users[0],
            description: 'The ski resort Niseko United – Annupuri/​Grand Hirafu/​Hanazono/​Niseko Village is located on Hokkaido (Japan). For skiing and snowboarding, there are 50.8 km of slopes available. 32 lifts transport the guests. The winter sports area is situated between the elevations of 255 and 1,188 m.',
            skilifts: '32',
            openingtimes: '08:30 - 20:30',
            slopeslength: '50.8km',
            adultticket: '¥ 8000,-',
            childticket: '¥ 6400,-',
            userRating: 4,
            numOfRatings: 0
          },    
          {
            name: 'Szymoszkowa',
            country: 'Poland',
            top_elevation: 1126,
            bottom_elevation: 865,
            lon: 19.9291,
            lat: 49.2929,
            image: 'https://i.imgur.com/kX9EqPL.jpg',
            user: users[0],
            description: 'The ski resort Szymoszkowa is located in Zakopane (Poland, Lesser Poland (Województwo małopolskie)). For skiing and snowboarding, there are 4 km of slopes available. 2 lifts transport the guests. The winter sports area is situated between the elevations of 865 and 1,126 m.',
            skilifts: '2',
            openingtimes: '09:00 - 20:00',
            slopeslength: '4km',
            adultticket: 'PLN 110,-',
            childticket: 'PLN 100,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Rosa Khutor',
            country: 'Russia',
            top_elevation: 2320,
            bottom_elevation: 940,
            lon: 43.6751,
            lat: 40.2927,
            image: 'https://i.imgur.com/aG74jWi.jpg',
            user: users[0],
            description: 'The ski resort Rosa Khutor is located in Krasnaya Polyana (Sochi) (Southern Russia, Krasnodar). For skiing and snowboarding, there are 102 km of slopes available. 26 lifts transport the guests. The winter sports area is situated between the elevations of 940 and 2,320 m.',
            skilifts: '26',
            openingtimes: '08:45 - 15.45',
            slopeslength: '102km',
            adultticket: 'RUB 3900,-',
            childticket: 'RUB 1900,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Zavyalikha',
            country: 'Russia',
            top_elevation: 840,
            bottom_elevation: 414,
            lon: 58.521716,
            lat: 54.795211,   
            image: 'https://i.imgur.com/5c90aSU.jpg',
            user: users[0],
            description: 'The ski resort Zavjalikha is located in the Chelyabinsk Oblast (Ural Federal District). For skiing and snowboarding, there are 22 km of slopes available. 4 lifts transport the guests. The winter sports area is situated between the elevations of 414 and 840 m.',
            skilifts: '4',
            openingtimes: '08:45 - 15.45',
            slopeslength: '22km',
            adultticket: 'RUB 2600,-',
            childticket: 'RUB 1600,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Bláfjöll',
            country: 'Iceland',
            top_elevation: 700,
            bottom_elevation: 460,
            lon: -21.6688,
            lat: 63.9855,   
            image: 'https://i.imgur.com/5zaMv33.jpg',
            user: users[0],
            description: 'The ski resort Bláfjöll is located in South Iceland (Iceland). For skiing and snowboarding, there are 15 km of slopes available. 15 lifts transport the guests. The winter sports area is situated between the elevations of 460 and 700 m.',
            skilifts: '15',
            openingtimes: '10:00 - 17.00',
            slopeslength: '15km',
            adultticket: 'ISK 3950,-',
            childticket: 'ISK 1500,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Big Wood',
            country: 'Russia',
            top_elevation: 1047,
            bottom_elevation: 380,
            lon: 33.693718,
            lat: 67.609813,   
            image: 'https://i.imgur.com/aFJKqNl.jpg',
            user: users[0],
            description: 'The ski resort Big Wood is located in the Murmansk Oblast (Northwest Russia). For skiing and snowboarding, there are 26.7 km of slopes available. 8 lifts transport the guests. The winter sports area is situated between the elevations of 380 and 1,047 m.',
            skilifts: '8',
            openingtimes: '10:00 - 20.00',
            slopeslength: '26.7km',
            adultticket: 'RUB 1600,-',
            childticket: 'RUB 1300,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Ulaanbaatar',
            country: 'Mongolia',
            top_elevation: 1596,
            bottom_elevation: 1376,
            lon: 107.033691,
            lat: 47.878179,
            image: 'https://i.imgur.com/YnfSlbG.jpg',
            user: users[0],
            description: 'The ski resort Sky Resort – Ulaanbaatar is located in Ulaanbaatar (Mongolia). For skiing and snowboarding, there are 6 km of slopes available. 4 lifts transport the guests. The winter sports area is situated between the elevations of 1,376 and 1,596 m.',
            skilifts: '4',
            openingtimes: '09:00 - 22:00',
            slopeslength: '6km',
            adultticket: 'RUB 1600,-',
            childticket: 'RUB 1300,-',
            userRating: 4,
            numOfRatings: 0
          },
          {
            name: 'Oukaimeden',
            country: 'Morocco',
            top_elevation: 2610,
            bottom_elevation: 3268,
            lon: -7.864063,
            lat: 31.202755,
            image: 'https://i.imgur.com/ewCHk05.jpg',
            user: users[0],
            description: 'The ski resort Oukaïmeden is located in the Marrakesh-Tensift-El Haouz Region (Morocco). For skiing and snowboarding, there are 10 km of slopes available. 7 lifts transport the guests. The winter sports area is situated between the elevations of 2,610 and 3,268 m.',
            skilifts: '7',
            openingtimes: '09:00 - 22:00',
            slopeslength: '10km',
            adultticket: 'MAD 500,-',
            childticket: 'MAD 700,-',
            userRating: 4,
            numOfRatings: 0
          }
        ])
      })

      .then(resorts => {
        console.log(`${resorts.length} resorts have been created.`)
        return resorts
      })

      .catch(err => {
        console.log(err)
      })

      .finally(() => {

        mongoose.connection.close()

      })
  }
)
